/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author Rudia
 */
public class frameUtama extends javax.swing.JFrame {

    /**
     * Creates new form FrameUtama
     */
    public frameUtama() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFormRegKtp = new javax.swing.JButton();
        btnFormRegKK = new javax.swing.JButton();
        btnFormPengKTP = new javax.swing.JButton();
        btnFormPengKK = new javax.swing.JButton();
        btnFormLaporan = new javax.swing.JButton();
        btnFormDataPemilik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFormRegKtp.setText("Form Data Registrasi KTP");
        btnFormRegKtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormRegKtpActionPerformed(evt);
            }
        });

        btnFormRegKK.setText("Form Data Registrasi KK");
        btnFormRegKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormRegKKActionPerformed(evt);
            }
        });

        btnFormPengKTP.setText("Form Data Pengambilan KTP");
        btnFormPengKTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormPengKTPActionPerformed(evt);
            }
        });

        btnFormPengKK.setText("Form Data Pengambilan KK");
        btnFormPengKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormPengKKActionPerformed(evt);
            }
        });

        btnFormLaporan.setText("Form Data Laporan");
        btnFormLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormLaporanActionPerformed(evt);
            }
        });

        btnFormDataPemilik.setText("Form Data Pemilik");
        btnFormDataPemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormDataPemilikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFormPengKTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnFormRegKtp)
                        .addComponent(btnFormRegKK, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(btnFormLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormPengKK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormDataPemilik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFormPengKTP, btnFormRegKK, btnFormRegKtp});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnFormRegKtp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFormRegKK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFormPengKTP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFormPengKK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFormLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFormDataPemilik)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormRegKtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormRegKtpActionPerformed
        new frameRegKtp().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnFormRegKtpActionPerformed

    private void btnFormRegKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormRegKKActionPerformed
        new frameRegKK().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFormRegKKActionPerformed

    private void btnFormPengKTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormPengKTPActionPerformed
        new framePengambilanKtp().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFormPengKTPActionPerformed

    private void btnFormPengKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormPengKKActionPerformed
        new framePengambilanKK().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFormPengKKActionPerformed

    private void btnFormLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormLaporanActionPerformed
        new frameLaporan().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFormLaporanActionPerformed

    private void btnFormDataPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormDataPemilikActionPerformed
        new frameDataPemilik().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFormDataPemilikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormDataPemilik;
    private javax.swing.JButton btnFormLaporan;
    private javax.swing.JButton btnFormPengKK;
    private javax.swing.JButton btnFormPengKTP;
    private javax.swing.JButton btnFormRegKK;
    private javax.swing.JButton btnFormRegKtp;
    // End of variables declaration//GEN-END:variables
}
